In [2]:
import pandas as pd
df = pd.read_excel(r"C:\Users\MV RK REDDY\Downloads\Copy of Afficionado Coffee Roasters.xlsx")
print(df)

        transaction_id  year transaction_time  transaction_qty  store_id  \
0                    1  2025         07:06:11                2         5
1                    2  2025         07:08:56                2         5
2                    3  2025         07:14:04                2         5
3                    4  2025         07:20:24                1         5
4                    5  2025         07:22:41                2         5
...                ...   ...              ...              ...       ...
149111          149452  2025         20:18:41                2         8
149112          149453  2025         20:25:10                2         8
149113          149454  2025         20:31:34                1         8
149114          149455  2025         20:57:19                1         8
149115          149456  2025         20:57:19                2         8

         store_location  product_id  unit_price    product_category  \
0       Lower Manhattan          32        3.00              Coffee
1       Lower Manhattan          57        3.10                 Tea
2       Lower Manhattan          59        4.50  Drinking Chocolate
3       Lower Manhattan          22        2.00              Coffee
4       Lower Manhattan          57        3.10                 Tea
...                 ...         ...         ...                 ...
149111   Hell's Kitchen          44        2.50                 Tea
149112   Hell's Kitchen          49        3.00                 Tea
149113   Hell's Kitchen          45        3.00                 Tea
149114   Hell's Kitchen          40        3.75              Coffee
149115   Hell's Kitchen          64        0.80            Flavours

                 product_type               product_detail
0       Gourmet brewed coffee                  Ethiopia Rg
1             Brewed Chai tea     Spicy Eye Opener Chai Lg
2               Hot chocolate            Dark chocolate Lg
3                 Drip coffee  Our Old Time Diner Blend Sm
4             Brewed Chai tea     Spicy Eye Opener Chai Lg
...                       ...                          ...
149111      Brewed herbal tea                Peppermint Rg
149112       Brewed Black tea         English Breakfast Lg
149113      Brewed herbal tea                Peppermint Lg
149114       Barista Espresso                   Cappuccino
149115          Regular syrup               Hazelnut syrup

[149116 rows x 11 columns]

In [3]:
df.shape

(149116, 11)

In [4]:
df.columns

Index(['transaction_id', 'year', 'transaction_time', 'transaction_qty',
       'store_id', 'store_location', 'product_id', 'unit_price',
       'product_category', 'product_type', 'product_detail'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   year              149116 non-null  int64
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  str
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
dtypes: float64(1), int64(5), object(1), str(4)
memory usage: 12.5+ MB

In [6]:
df.describe()

,transaction_id,year,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116.0,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2025.0,1.438276,5.342063,47.918607,3.382219
std,43153.600016,0.0,0.542509,2.074241,17.930020,2.658723
min,1.000000,2025.0,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,2025.0,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,2025.0,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2025.0,2.000000,8.000000,60.000000,3.750000
max,149456.000000,2025.0,8.000000,8.000000,87.000000,45.000000

In [7]:
f= df.duplicated().sum()
print(f)

0

In [8]:
df["transaction_id"].duplicated().sum()

np.int64(0)

In [9]:
r = df.isnull().sum()
print(r)

transaction_id      0
year                0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [10]:
df["revenue"] = df["transaction_qty"] * df["unit_price"]

In [11]:
df["transaction_time"] = pd.to_datetime(
    df["transaction_time"],
    format="%H:%M:%S"
)

In [12]:
df["hour"] = df["transaction_time"].dt.hour

In [13]:
df

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,revenue,hour
0,1,2025,1900-01-01 07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,7
1,2,2025,1900-01-01 07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,7
2,3,2025,1900-01-01 07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,7
3,4,2025,1900-01-01 07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,7
4,5,2025,1900-01-01 07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2025,1900-01-01 20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,20
149112,149453,2025,1900-01-01 20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,20
149113,149454,2025,1900-01-01 20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,20
149114,149455,2025,1900-01-01 20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,20
149115,149456,2025,1900-01-01 20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,20

In [14]:
df.groupby("hour")["product_category"].value_counts().sort_values(ascending=False)

hour  product_category
10    Coffee                7006
8     Coffee                6687
9     Coffee                6652
      Tea                   5296
10    Tea                   5271
                            ...
18    Packaged Chocolate      10
20    Coffee beans             9
      Packaged Chocolate       7
      Branded                  4
      Loose Tea                2
Name: count, Length: 135, dtype: int64

In [15]:
df.groupby("store_location")["product_category"].value_counts().sort_values(ascending=False)

store_location   product_category
Hell's Kitchen   Coffee                20187
Astoria          Coffee                20025
Lower Manhattan  Coffee                18204
Astoria          Tea                   16260
Hell's Kitchen   Tea                   15277
Lower Manhattan  Tea                   13912
                 Bakery                 7890
Hell's Kitchen   Bakery                 7617
Astoria          Bakery                 7289
                 Drinking Chocolate     4300
Hell's Kitchen   Drinking Chocolate     3763
Lower Manhattan  Drinking Chocolate     3405
                 Flavours               2930
Hell's Kitchen   Flavours               2370
Astoria          Flavours               1490
Hell's Kitchen   Coffee beans            720
Lower Manhattan  Coffee beans            531
Astoria          Coffee beans            502
Hell's Kitchen   Loose Tea               485
Lower Manhattan  Loose Tea               381
                 Branded                 349
Astoria          Loose Tea               344
                 Branded                 279
Hell's Kitchen   Packaged Chocolate      197
Lower Manhattan  Packaged Chocolate      180
Hell's Kitchen   Branded                 119
Astoria          Packaged Chocolate      110
Name: count, dtype: int64

In [16]:
df.groupby("product_category")["revenue"].sum().sort_values(ascending=False)

product_category
Coffee                269952.45
Tea                   196405.95
Bakery                 82315.64
Drinking Chocolate     72416.00
Coffee beans           40085.25
Branded                13607.00
Loose Tea              11213.60
Flavours                8408.80
Packaged Chocolate      4407.64
Name: revenue, dtype: float64

In [17]:
df.groupby("store_location")["revenue"].sum().sort_values(ascending=False)

store_location
Hell's Kitchen     236511.17
Astoria            232243.91
Lower Manhattan    230057.25
Name: revenue, dtype: float64

In [18]:
df["hour"].value_counts()

hour
10    18545
9     17764
8     17654
7     13428
11     9766
16     9093
15     8979
14     8933
17     8745
13     8714
12     8708
18     7498
19     6092
6      4594
20      603
Name: count, dtype: int64

In [19]:
df.groupby("hour")["revenue"].sum().sort_values(ascending=False)

hour
10    88673.39
9     85169.53
8     82699.87
7     63526.47
11    46319.14
15    41733.10
14    41304.74
16    41122.75
13    40367.45
12    40192.79
17    40134.31
18    34286.20
19    28446.68
6     21900.27
20     2935.64
Name: revenue, dtype: float64

In [20]:
def time_bucket(hour):
    if 6 < hour < 11:
        return "morning"
    if 12 < hour < 16:
        return "after noon"
    if 17 < hour < 21:
        return "evening"
    else :
        return "late hour"
df["time_bucket"] = df["hour"].apply(time_bucket)

In [21]:
df.groupby("time_bucket")["revenue"].sum().sort_values(ascending=False)

time_bucket
morning       320069.26
late hour     189669.26
after noon    123405.29
evening        65668.52
Name: revenue, dtype: float64

In [22]:
df.to_csv(r"C:\Users\MV RK REDDY\OneDrive\Documents\coffee_sales_cleaned.csv", index=False)